config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "shiurim#index"
  resources :users
  resources :shiurim
  resource :sessions, only: %i[new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/learner.rb
class Learner < ApplicationRecord
  belongs_to :shiur

  validates :name, presence: true
end

app/models/shiur.rb
class Shiur < ApplicationRecord
  has_many :learners

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/learners_controller.rb
class LearnersController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:email]

    if user&.authenticate params[:password]
      session[:user_id] = user.id
      redirect_to user, notice: "Welcome back #{user.name}!"
    else
      redirect_to new_sessions_url, alert: "That email/password combination was invalid."
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to :root
  end
end

app/controllers/shiurim_controller.rb
# frozen_string_literal: true

class ShiurimController < ApplicationController
  def index
    @shiurim = Shiur
               .order(:importance)
               .where("importance < ?", 3)
  end

  def show
    @shiur = Shiur.find params[:id]
  end

  def edit
    @shiur = Shiur.find params[:id]
  end

  def update
    @shiur = Shiur.find params[:id]

    if @shiur.update shiur_params
      redirect_to @shiur
    else
      render :edit
    end
  end

  def new
    @shiur = Shiur.new
  end

  def create
    @shiur = Shiur.new shiur_params

    if @shiur.save
      redirect_to shiur
    else
      render :new
    end
  end

  def destroy
    Shiur.find(params[:id]).destroy!

    redirect_to shiurim_url
  end

  private

  def shiur_params
    params.require(:shiur).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Welcome, #{@user.name}!"
    else
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/learners_helper.rb
module LearnersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shiurim_helper.rb
module ShiurimHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_session.html.erb
<% if flash[:notice] %>
  <div class="success"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
  <div class="error"><%= flash[:alert] %></div>
<% end %>

app/views/layouts/_user_header.html.erb
<% if current_user %>
  <%= link_to current_user.name, current_user %>
  <%= link_to "Sign Out", sessions_path, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_sessions_path %>
  <%= link_to "Sign Up", new_user_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsShiurim</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/user_header" %>

    <%= render "layouts/session" %>

    <%= yield %>
  </body>
</html>

app/views/shiurim/_form.html.erb
<% if @shiur.errors.any? %>
  <h2>Errors</h2>
  <ul>
    <% @shiur.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @shiur, local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <br>
  
  <%= form.submit %>
<% end %>

app/views/shiurim/edit.html.erb
<%= render "form", event: @event%>

<%= link_to "Cancel", @shiur %>

app/views/shiurim/index.html.erb
<ul>
  <% @shiurim.each do |shiur| %>
    <li>
      <a href="<%= url_for shiur %>"><strong><%= shiur.name %></strong></a>
      <br>Should take about <%= shiur.time %> of an hour.
    </li>
  <% end %>
</ul>

<div>
  <%= link_to "New Shiur", new_shiur_path %>
</div>

app/views/shiurim/new.html.erb
<%= render "form", event: @event %>

<%= link_to "Cancel", shiurim_path %>

app/views/shiurim/show.html.erb
<%= @shiur.name %>

<br>

<h2>Who's learning?</h2>

<ul>
  <% @shiur.learners.each do |l| %>
    <li><%= l.name %> <i><%= "Active" if l.active %></i></li>
  <% end %>
</ul>

<br>

<%= link_to("Back", shiurim_path) %>

<br>

<%= link_to("Edit", edit_shiur_path(@shiur)) %>

<br>

<%= link_to "Delete", @shiur, method: :delete, data: { confirm: "Are you sure you want to delete this shiur?" } %>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <br>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <br>
 
  <%= f.label :password %>
  <%= f.password_field :password %>

  <br>
 
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <br>
 
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |u| %>
    <li><%= link_for u.name, u %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "users/form" %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p><%= @user.email %></p>

<%= link_to "Edit", edit_user_path(@user) %>